apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/istio
  - crds/calico
  - crds/kyverno
  - istio
  - calico 
  - kyverno
commonLabels:
  managed-by: kustomize
  environment: base
