apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico/kustomization.yaml
  - kyverno/kustomization.yaml
  - istio/

commonLabels:
  managed-by: kustomize
  environment: base
