apiVersion: v1
kind: Namespace
metadata:
  name: calico-system
---
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  variant: Calico
  registry: docker.io
  calicoNetwork:
    bgp: Disabled
    ipPools:
    - blockSize: 26
      cidr: 10.10.0.0/16
      encapsulation: VXLAN
      natOutgoing: Enabled
---
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: calico-apiserver
spec:
  {}
